# Build binary for alpine
FROM golang:1.13-alpine3.10 as build

RUN mkdir -p /go/src/github.com/Meromen/mfc-backend
WORKDIR /go/src/github.com/Meromen/mfc-backend
COPY ./ ./

RUN cd cmd/mfc-api && CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -installsuffix cgo

# Create actual image
FROM alpine:3.10

# dependencies
RUN apk --update upgrade && \
    apk add curl ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*

# copy binary
RUN mkdir -p /cmd/mfc-api

COPY --from=build /go/src/github.com/Meromen/mfc-backend/cmd/mfc-api/ /cmd/mfc-api/
CMD cd /cmd/mfc-api && ls -a && rm ./main.go

CMD "/cmd/mfc-api/mfc-api"
